DROP TABLE IF EXISTS CREDITCARDDETAIL;

CREATE TABLE CREDITCARDDETAIL (
  ID NUMBER(10) NOT NULL,
  NAME VARCHAR2(50) NOT NULL,
  CARDNUMBER VARCHAR2(20) NOT NULL,
  BALANCE VARCHAR2(10) NOT NULL,
  CARDLIMIT VARCHAR2(10) NOT NULL,
  CREATEDDATETIME TIMESTAMP,
   PRIMARY KEY (ID)
);